export const letterDistributions = {
  en: {
    A: { c: 9, p: 1 },
    B: { c: 2, p: 3 },
    C: { c: 2, p: 3 },
    D: { c: 4, p: 2 },
    E: { c: 12, p: 1 },
    F: { c: 2, p: 4 },
    G: { c: 3, p: 2 },
    H: { c: 2, p: 4 },
    I: { c: 9, p: 1 },
    J: { c: 1, p: 8 },
    K: { c: 1, p: 5 },
    L: { c: 4, p: 1 },
    M: { c: 2, p: 3 },
    N: { c: 6, p: 1 },
    O: { c: 8, p: 1 },
    P: { c: 2, p: 3 },
    Q: { c: 1, p: 10 },
    R: { c: 6, p: 1 },
    S: { c: 4, p: 1 },
    T: { c: 6, p: 1 },
    U: { c: 4, p: 1 },
    V: { c: 2, p: 4 },
    W: { c: 2, p: 4 },
    X: { c: 1, p: 8 },
    Y: { c: 2, p: 4 },
    Z: { c: 1, p: 10 },
  },
  de: {
    E: { c: 15, p: 1 },
    N: { c: 9, p: 1 },
    S: { c: 7, p: 1 },
    I: { c: 6, p: 1 },
    R: { c: 6, p: 1 },
    T: { c: 6, p: 1 },
    U: { c: 6, p: 1 },
    A: { c: 5, p: 1 },
    D: { c: 4, p: 1 },
    H: { c: 4, p: 2 },
    G: { c: 3, p: 2 },
    L: { c: 3, p: 2 },
    O: { c: 3, p: 2 },
    M: { c: 4, p: 3 },
    B: { c: 2, p: 3 },
    W: { c: 1, p: 3 },
    Z: { c: 1, p: 3 },
    C: { c: 2, p: 4 },
    F: { c: 2, p: 4 },
    K: { c: 2, p: 4 },
    P: { c: 1, p: 4 },
    Ä: { c: 1, p: 6 },
    J: { c: 1, p: 6 },
    Ü: { c: 1, p: 6 },
    V: { c: 1, p: 6 },
    Ö: { c: 1, p: 8 },
    X: { c: 1, p: 8 },
    Q: { c: 1, p: 10 },
    Y: { c: 1, p: 10 },
  },
  es: {
    A: { c: 12, p: 1 },
    E: { c: 12, p: 1 },
    O: { c: 9, p: 1 },
    S: { c: 6, p: 1 },
    I: { c: 6, p: 1 },
    U: { c: 5, p: 1 },
    N: { c: 5, p: 1 },
    L: { c: 4, p: 1 },
    R: { c: 5, p: 1 },
    T: { c: 4, p: 1 },
    C: { c: 4, p: 2 },
    D: { c: 5, p: 2 },
    G: { c: 2, p: 2 },
    B: { c: 2, p: 3 },
    M: { c: 2, p: 3 },
    P: { c: 2, p: 3 },
    H: { c: 2, p: 4 },
    F: { c: 1, p: 4 },
    V: { c: 1, p: 4 },
    Y: { c: 1, p: 4 },
    J: { c: 1, p: 8 },
    Ñ: { c: 1, p: 8 },
    X: { c: 1, p: 8 },
    Q: { c: 1, p: 5 }, // Q is 5 in Spanish Scrabble
    Z: { c: 1, p: 10 },
  },
  fr: {
    E: { c: 15, p: 1 },
    A: { c: 9, p: 1 },
    I: { c: 8, p: 1 },
    N: { c: 6, p: 1 },
    O: { c: 6, p: 1 },
    R: { c: 6, p: 1 },
    S: { c: 6, p: 1 },
    T: { c: 6, p: 1 },
    U: { c: 6, p: 1 },
    L: { c: 5, p: 1 },
    D: { c: 3, p: 2 },
    M: { c: 3, p: 2 },
    G: { c: 2, p: 2 },
    B: { c: 2, p: 3 },
    C: { c: 2, p: 3 },
    P: { c: 2, p: 3 },
    F: { c: 2, p: 4 },
    H: { c: 2, p: 4 },
    V: { c: 2, p: 4 },
    J: { c: 1, p: 8 },
    Q: { c: 1, p: 8 },
    K: { c: 1, p: 10 },
    W: { c: 1, p: 10 },
    X: { c: 1, p: 10 },
    Y: { c: 1, p: 10 },
    Z: { c: 1, p: 10 },
  },
  ca: {
    E: { c: 13, p: 1 },
    A: { c: 12, p: 1 },
    I: { c: 8, p: 1 },
    R: { c: 8, p: 1 },
    S: { c: 8, p: 1 },
    N: { c: 6, p: 1 },
    O: { c: 5, p: 1 },
    T: { c: 5, p: 1 },
    L: { c: 4, p: 1 },
    U: { c: 4, p: 1 },
    C: { c: 3, p: 2 },
    D: { c: 3, p: 2 },
    M: { c: 3, p: 2 },
    B: { c: 2, p: 3 },
    G: { c: 2, p: 3 },
    P: { c: 2, p: 3 },
    F: { c: 1, p: 4 },
    V: { c: 1, p: 4 },
    H: { c: 1, p: 8 },
    J: { c: 1, p: 8 },
    Q: { c: 1, p: 8 },
    Z: { c: 1, p: 8 },
    Ç: { c: 1, p: 10 },
    X: { c: 1, p: 10 },
    Y: { c: 1, p: 10 },
  },
  it: {
    A: { c: 14, p: 1 },
    B: { c: 3, p: 5 },
    C: { c: 6, p: 2 },
    D: { c: 3, p: 5 },
    E: { c: 14, p: 1 },
    F: { c: 3, p: 5 },
    G: { c: 2, p: 8 },
    H: { c: 2, p: 8 },
    I: { c: 14, p: 1 },
    L: { c: 6, p: 3 },
    M: { c: 6, p: 3 },
    N: { c: 6, p: 3 },
    O: { c: 14, p: 1 },
    P: { c: 3, p: 5 },
    Q: { c: 2, p: 10 },
    R: { c: 6, p: 2 },
    S: { c: 6, p: 2 },
    T: { c: 6, p: 2 },
    U: { c: 6, p: 3 },
    V: { c: 3, p: 5 },
    Z: { c: 2, p: 8 },
    // Foreign letters included in the game
    J: { c: 1, p: 10 },
    K: { c: 1, p: 10 },
    W: { c: 1, p: 10 },
    X: { c: 1, p: 10 },
    Y: { c: 1, p: 10 },
  },
};

export const alphabets = {
  en: "abcdefghijklmnopqrstuvwxyz",
  de: "abcdefghijklmnopqrstuvwxyzäöü",
  es: "abcdefghijklmnñopqrstuvwxyz",
  fr: "abcdefghijklmnopqrstuvwxyzç",
  ca: "abcdefghijklmnopqrstuvwxyzç",
  it: "abcdefghijklmnopqrstuvwxyz",
};

export const flags = {
  en: "🇬🇧",
  de: "🇩🇪",
  es: "🇪🇸",
  fr: "🇫🇷",
  ca: "🇦🇩",
  it: "🇮🇹",
};

export const affixTiles = {
  en: [
    { letters: "ING", points: 2 },
    { letters: "ER", points: 1 },
    { letters: "ION", points: 2 },
  ],
  es: [
    { letters: "ADO", points: 2 },
    { letters: "IDO", points: 2 },
    { letters: "MENTE", points: 3 },
  ],
  ca: [
    { letters: "ANT", points: 2 },
    { letters: "INT", points: 2 },
    { letters: "ACIO", points: 3 },
  ],
  fr: [
    { letters: "EUR", points: 2 },
    { letters: "IQUE", points: 3 },
    { letters: "MENT", points: 2 },
  ],
  de: [
    { letters: "UNG", points: 2 },
    { letters: "HEIT", points: 2 },
    { letters: "LICH", points: 2 },
  ],
  it: [
    { letters: "ARE", points: 2 },
    { letters: "ERE", points: 2 },
    { letters: "IRE", points: 2 },
    { letters: "MENTO", points: 3 },
    { letters: "ZIONE", points: 3 },
  ],
};

export const BLACK_TILES_PER_ROUND = (round) => {
  const tiles = {
    1: 2,
    2: 2,
    3: 3,
    4: 3,
    5: 5,
    6: 5,
    7: 8,
    8: 8,
    9: 13,
    10: 13,
  };
  if (round < 1) {
    return 0;
  }
  if (round > 10) {
    return tiles[10];
  }
  return tiles[round];
};

export const BLOCKED_SLOTS_PER_ROUND = {
  1: { min: 0, max: 0 },
  2: { min: 0, max: 2 },
  3: { min: 0, max: 3 },
  4: { min: 0, max: 3 },
  5: { min: 0, max: 4 },
  6: { min: 0, max: 4 },
  7: { min: 0, max: 5 },
  8: { min: 0, max: 5 },
  9: { min: 0, max: 6 },
  10: { min: 0, max: 6 },
};

export const GRID_SIZE = 16;
export const ANSWER_SLOTS = 10;
export const TOTAL_ROUNDS = Infinity;
export const MIN_WORD_LENGTH = 4;
export const bonusSlots = { 4: 5, 5: 5, 6: 5, 7: 5, 8: 10, 9: 20 };

export let props = {
  version: null,
  seedWord: "", // Add property for the seed word
};
